spring.application.name=dreamcart-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/dreamcart_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
debug=true
http=//localhost:8080/v3/api-docs
server.port=8080
jwt.secret=g7K8mN3pQ5rT2wX9yZ4aB6cD1eF0hJ7kL8mN3pQ5rT2wX9yZ4aB6cD1eF0hJ7k=
jwt.expiration=86400000

#############################################
# Email Configuration
#############################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ronin.sr95@gmail.com
spring.mail.password=YOUR_APP_PASSWORs

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true